name: Patch Terraform and Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go and install gox
      run: |
        go install github.com/mitchellh/gox@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Extract base version
      run: |
        BASE_VERSION="${GITHUB_REF_NAME%%-*}"
        echo "BASE_VERSION=$BASE_VERSION" >> $GITHUB_ENV

    - name: Clone Terraform and apply patch
      run: |
        git clone --branch "v$BASE_VERSION" https://github.com/hashicorp/terraform.git
        cd terraform
        git checkout -b patched
        echo "${GITHUB_REF_NAME}" | tee version/VERSION
        curl -fsSL https://patch-diff.githubusercontent.com/raw/zerosuxx/terraform-fork/pull/1.diff | git apply -v -

    - name: Build with gox
      working-directory: ./terraform
      run: |
        go mod download
        gox -os="linux darwin" -arch="amd64 arm64" \
            -ldflags "${LD_FLAGS}" \
            -output="build/terraform-{{.Arch}}-{{.OS}}"

        for f in build/*arm64*; do
          mv -v "$f" "${f/arm64/aarch64}"
        done
      env:
        LD_FLAGS: "-s -w -X 'github.com/hashicorp/terraform/version.dev=no'"
        GOFLAGS: "-mod=readonly"
        CGO_ENABLED: 0

    - name: Upload binaries
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: terraform/build/terraform-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
